# fly.toml app configuration file generated for phantom-cloud-engine on 2026-09-15T16:33:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phantom-cloud-engine'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
